- name: Get start timestamp
  hosts: cloud
  connection: local
  tasks:
    - set_fact:
        starttime: "{{ ansible_date_time }}"
        status_flag: "Success"
        uid: "{{ uid }}"
        contentrepo: "{{ contentrepo }}"
        req_id: "{{ reqId }}"

    - set_fact:
        work_dir: "{{ playbook_dir }}/run{{ req_id }}"
        kubepath: "{{ playbook_dir }}/vars/kubeconfig"

    - name: Create working directory
      file:
        path: "{{ work_dir }}/kube"
        state: "{{ item }}"
      with_items:
        - absent
        - directory

    - include_tasks: processkubeconfig.yml

    - name: Get bnd profile pod name
      shell:
        kubectl --kubeconfig {{ kubepath }}
        get pods | grep bndsampler | awk '{print $1}'
      register: bndsampler_output

    - name: Generate bnd report if sampler is found
      include_tasks: genbndreport.yml
      when: bndsampler_output.stdout_lines|length > 0
