- debug:
    msg: "outer item={{ testitem }}"

- name: Run test "{{ testitem.name }}"
  command: >-
    kubectl --kubeconfig {{ kubepath }} apply
    -f {{ work_dir }}/job{{ my_idx }}.yml -n {{ namespace }}

- name: adding to parallel job list
  set_fact:
    runningjobs: |
      {{ runningjobs + [{'name':testitem.name, 'operation':testitem.operation,
      'idx':my_idx, 'loadSpread':testitem.loadSpread}] }}

- include_tasks: jobstatuscheck.yml
  loop: "{{ runningjobs }}"
  loop_control:
    loop_var: jobitem
    index_var: jobidx
  when: (testitem.waitUntilFinish | default(true)) == true

- name: reset the parallel job list
  set_fact:
    runningjobs: "{{ [] }}"
  when: (testitem.waitUntilFinish | default(true)) == true